version: '3.1'

services:
  application:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .dev.env
    links:
      - db
    networks:
      - backend
    depends_on:
      - db
    command: 
      ["./wait-for-it.sh", "db:3306", "-t", "30", "--", "npm", "run", "test:e2e"]
networks:
  backend:
    driver: "bridge"